# Generated by Django 2.0 on 2018-04-12 16:19

from django.db import migrations, models
import sprintercarsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintercarsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to=sprintercarsapp.models.upload_slider_image)),
            ],
        ),
    ]
