# Generated by Django 2.0 on 2018-04-13 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintercarsapp', '0002_sliderimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('url_slug', models.SlugField(editable=False)),
            ],
        ),
    ]
